# Travis can building for Linux (Ubuntu 14.04 x64) and OS X (El Capitan)
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: generic

    - os: osx
      sudo: required
      language: generic

before_install:
  # OS and default Python info
  - uname -a
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then python3 -c "import sys; print(sys.executable)"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo python3 -c "import sys; print(sys.executable)"; fi

install:
  # Python 3 and pip 3 installation are OS dependant
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then bash package/install_osx.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash package/install_linux.sh; fi

  # Install Mu dependencies (PyQt & QScintilla will be absorbed in requirements.txt once ready)
  - sudo pip3 install -r requirements.txt
  - sudo pip3 install PyQt5
  - sudo pip3 install QScintilla

  # Install packaging dependencies, macOS depends on update not yet released https://github.com/pyinstaller/pyinstaller/pull/1965
  - sudo pip3 install git+git://github.com/pyinstaller/pyinstaller.git@483c819d6a256b58db6740696a901bd41c313f0c

  # Check everything was correctly installed
  - echo $PATH
  - python3 --version
  - python3 -c "import struct; print(struct.calcsize('P') * 8)"
  - python3 -c "import sys; print(sys.executable)"
  - pip3 --version
  - sudo pip3 --version
  - pip3 freeze
  - python3 -c "import PyQt5"
  - python3 -c "import PyQt5.Qsci"

script:
  # Run tests
  - make check
  - make clean

  # Package it
  - pyinstaller package/pyinstaller.spec
  - du -sk dist/
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mv dist/mu dist/mu-$(date '+%Y-%m-%d_%H_%M_%S'); fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cd dist && zip --symlinks -r mu-$(date '+%Y-%m-%d_%H_%M_%S').zip mu.app && rm -r mu.app && rm mu && cd ..; fi

# Deploy the build version in an S3 bucket
deploy:
  provider: s3
  access_key_id: AKIAJYJV7NN6HVHCX5NQ
  secret_access_key:
    secure: QHLfRUdFQX+TejhRBkgNvySkaQOskXji+iduIvKRtzvvhyr3QJHKcMNtO426GRFyKhz6sK3shqn4d5iu/m03gtbv+u1pL9pp0J2GEePzQVP8v24q9Y3oxaXaA7Tm7L2vSIrB7uhJvG5D9H0bVL9my61JvXhvySH47jLvhqHH4F9LdPzby1DXds1Z+R4YNMKE0Z4KmNOhiBHkmKdDcp61fZ91gGiScFIjaXvDb50zdGKjXTQy2t4OtFt4kVbTZWijzxKPCSLZkErfcdNNrCNeMEktk6IEV2KVru9XhDNzzslWwwsR1r2hQI39oVULa3fYXK6W7am8WXVZ6cnJB+yBsNWro3Tp5oiNCWSe6fKDEp+Io+qyhZ+R5PSdzhyRYPUHPCIY/fP/dap/4M/MAO3hZFA3mxjK/vUOc6mtMD/wTE659K4/i7PNYtKFndXXpLpYHHaTis44NLZFIxvs9wWG/ljToYDDK20vG317k5TZUZB/6EipW1DeoO/9qBUxgTdfJypp58kcZNvntUVa4ezf/Bx01ZCMFAk234l7+xAFYI7+m9ITqAPlKWI230Ki5ShzyV+kYcI/GS9cT75iok6+zIWWfyQhKUMDYZ1qb/UDM5Gz9RXoIah0UJTjFd4b3bO6Awdrs2V5Vv2EgMWuKDaHs1s3uONH+PGTluROuqFju/s=
  bucket: ardublockly-builds
  skip_cleanup: true
  local-dir: dist/
  upload-dir: microbit/$TRAVIS_OS_NAME
  acl: public_read
  on:
    repo: mu-editor/mu
    branch: [master]

notifications:
  email:
    on_success: change
    on_failure: change
